# ============================== Version ================================ #
# ======================================================================= #

version: 0.0.0+0

# ============================= Information ============================= #
# ======================================================================= #

name: mono
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

# ============================ Dependencies ============================= #
# ======================================================================= #

dependencies:
  flutter:
    sdk: flutter

  melos: '^3.1.0'

dev_dependencies:
  flutter_lints: '^2.0.0'

# ================================ Assets =============================== #
# ======================================================================= #

flutter:
  uses-material-design: true