# ============================== Version ================================ #
# ======================================================================= #

version: 0.0.0+0

# ============================= Information ============================= #
# ======================================================================= #

name: library
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

# ============================ Dependencies ============================= #
# ======================================================================= #

dependencies:
  flutter:
    sdk: flutter

  app:
    path: ../app
  core:
    path: ../core
  theme:
    path: ../theme
  widget:
    path: ../widget

dev_dependencies:
  flutter_lints: '^2.0.0'

# ================================ Assets =============================== #
# ======================================================================= #

flutter:
  uses-material-design: true